trigger:
- master

stages:
- stage: BuildStg
  jobs:
  - job: build
    pool: 
      name: Azure Pipelines
      vmImage: ubuntu-18.04
    steps:
    - task: CmdLine@2
      displayName: 'Get version info'
      inputs:
        script: |
          echo "##vso[task.setvariable variable=aiv;isOutput=true]1.0.0"
        name: DetermineResult
    - task: CmdLine@2
      displayName: 'print ver'
      inputs:
        script: |
          echo $(DetermineResult.aiv)
      
  - job: build_2
    dependsOn: build
    variables:
      aiv: $[ dependencies.build.outputs['DetermineResult.aiv'] ]
    steps:
    - script: |
        echo "aiv=$(aiv)"
