trigger:
- master

pool: 
  name: Azure Pipelines
  vmImage: ubuntu-18.04

stages:
- stage: buildStg
  jobs:
  # Set an output variable from job A
  - job: A
    steps:
    - powershell: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the value"
      name: setvarStep
    - script: echo $(setvarStep.myOutputVar)

  # Map the variable into job B
  - job: B
    dependsOn: A
    variables:
      myVarFromJobA: $[ dependencies.A.outputs['myOutputVar'] ]  # map in the variable
                                                                            # remember, expressions require single quotes
    steps:
    - script: echo $(myVarFromJobA)
      name: echovar
