trigger:
- master

stages:
- stage: BuildStg
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: CmdLine@2
      displayName: 'Get version info'
      inputs:
        script: |
          div=1.0.0
          echo "##vso[task.setvariable variable=div]$div"
          test=vamshi
          echo "##vso[task.setvariable variable=test;isOutput=true]$test"
    - bash: |
        echo $(div)
        test=$(div)
        echo "##vso[task.setvariable variable=test;isOutput=true]$test"
      name: test

- stage: BuildDeploy
  dependsOn: BuildStg
  jobs:
  - job: build
    variables: 
      test: $[ stageDependencies.BuildStg.build.outputs['test.test'] ]
    steps:
    - task: CmdLine@2
      displayName: 'Get version'
      inputs:
        script: |
          echo $(test)
