trigger:
- master

stages:
- stage: BuildStg
  jobs:
  - job: build
    pool: 
      name: Azure Pipelines
      vmImage: ubuntu-18.04
    steps:
    - script: |
        echo "##vso[task.setvariable variable=aiv;isOutput=true]1.0.0"
    - script: |
        echo $(aiv)
      
  - job: build_2
    dependsOn: build
    variables:
      aiv: $[ dependencies.build.outputs['aiv'] ]
    steps:
    - script: |
        echo "aiv=$(aiv)"
