trigger:
- master

stages:
- stage: BuildStg
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: CmdLine@2
      displayName: 'Get version info'
      inputs:
        script: |
          div=1.0.0.0
          echo "##vso[task.setvariable variable=div;isOutput=true]$div"
    - task: CmdLine@2
      displayName: 'Get'
      inputs:
        script: |
          echo $(div)

- stage: BuildDeploy
  dependsOn: BuildStg
  jobs:
  - job: build
    variables: 
      div: $[ stageDependencies.BuildStg.build.outputs['div'] ]
    steps:
    - task: CmdLine@2
      displayName: 'Get version'
      inputs:
        script: |
          echo $(div)
