trigger:
- master

stages:
- stage: BuildStg
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: CmdLine@2
      displayName: 'Get version info'
      inputs:
        script: |
          div=1.0.0
          echo "##vso[task.setvariable variable=div]$div"
          test=vamshi
          echo "##vso[task.setvariable variable=test;isOutput=true]$test"
    - task: CmdLine@2
      displayName: 'Get'
      inputs:
        script: |
          echo $(div)
          echo $(test)

- stage: BuildDeploy
  dependsOn: BuildStg
  jobs:
  - job: build
    variables: 
      div: $[ stageDependencies.BuildStg.build.outputs['div'] ]
      test: $[ stageDependencies.BuildStg.build.outputs['test'] ]
    steps:
    - task: CmdLine@2
      displayName: 'Get version'
      inputs:
        script: |
          echo $(div)
          echo $(test)
