trigger:
- master

stages:
- stage: BuildStg
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - script: |
        div=1.0.0.0
        echo "##vso[task.setvariable variable=div;isOutput=true]$div"
      name: test
    - script: echo $(test.div)
      
  - job: build_2
    dependsOn: build
    pool:
      vmImage: 'ubuntu-18.04'
    variables:
      aiv: $[ dependencies.build.outputs['test.div'] ]
    steps:
    - script: echo "aiv=$(aiv)"
