trigger:
- master

stages:
- stage: BuildStg
  jobs:
    - job: build
      pool: 
        name: Azure Pipelines
        vmImage: ubuntu-18.04
      steps:
      - task: CmdLine@2
        displayName: 'Get version info'
        inputs:
          script: |
            aiv=1.0.0
            echo "##vso[task.setvariable variable=aiv;isOutput=true]$aiv"
          name: DetermineResult
      - script: echo $(DetermineResult.aiv)
        name: echovar
    - job: build_2
      dependsOn: build
      variables:
        aiv=$[ dependencies.build.outputs['DetermineResult.aiv'] ]
      steps:
      - script: |
          echo "aiv=$(aiv)"

- stage: BuildDeploy
  dependsOn: BuildStg
  jobs:
  - job: deploy
    variables:
      aiv=$[ dependencies.BuildStg.build.outputs['DetermineResult.aiv'] ]
    steps:
    - script: |
        echo "aiv=$(aiv)"
