trigger:
- master

stages:
- stage: BuildStg
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - script: echo "##vso[task.setvariable variable=aiv;isOutput=true]1.0.0"
      name: test
    - script: echo $(test.aiv)
      
  - job: build_2
    dependsOn: build
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      aiv: $[ dependencies.build.outputs['test.aiv'] ]
    steps:
    - script: echo "aiv=$(aiv)"
