trigger:
- master

stages:
  - template: template.yaml
  - stage: createShell
    dependsOn: BuildStg
    jobs:
    - job: 
      variables:
        div: $[ dependencies.BuildStg.build.outputs['DetermineResult.div'] ]
      steps:
      - bash: |
          echo "aiv=$(aiv)"
          echo "div=$(div)"
