trigger:
- master

pool: 
  name: Azure Pipelines
  vmImage: ubuntu-18.04

stages:
- stage: BuildStg
  jobs:
  - job: build
    steps:
    - script: |
        echo "##vso[task.setvariable variable=aiv;isOutput=true]1.0.0"
      name: test
    - script: |
        echo $(test.aiv)
      
  - job: build_2
    dependsOn: build
    variables:
      aiv: $[ dependencies.build.outputs['test.aiv'] ]
    steps:
    - script: |
        echo "aiv=$(aiv)"
