trigger:
- master

stages:
- template: template.yaml
- stage: BuildDeploy
  dependsOn: BuildStg
  jobs:
  - job: build
    variables: 
      test: $[ stageDependencies.BuildStg.build.outputs['test.test'] ]
    steps:
    - task: CmdLine@2
      displayName: 'Get version'
      inputs:
        script: |
          echo $(test)
