stages:
- stage: BuildShell
  dependsOn: BuildStg
  jobs: 
  - job: build_file
    variables: 
      test: $[ stageDependencies.BuildStg.build.outputs['test.test'] ]
    steps:
    - script: |
        mv $(build.artifactstagingdirectory)/scripts/test.sh $(build.artifactstagingdirectory)/acrconnect-installer-cli-$(test)[linux-x64].sh
        sed -i 's/aivversion/$(test)/g' $(build.artifactstagingdirectory)/acrconnect-installer-cli-$(test)[linux-x64].sh
        
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        artifactName: 'acrconnect-installer-cli-$(test)[linux-x64]'
