stages:
- stage: BuildShell
  dependsOn: BuildStg
  jobs: 
  - job: build_file
    pool: 
      name: Azure Pipelines
      vmImage: ubuntu-18.04
    variables: 
      test: $[ stageDependencies.BuildStg.build.outputs['test.test'] ]
    steps:
    - script: |
        sudo ls linux-out
        
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: 'linux-out'
        artifactName: 'acrconnect-installer-cli-$(test)[linux-x64]'
