stages:
- stage: BuildShell
  dependsOn: BuildStg
  jobs: 
  - job: build_file
    variables: 
      test: $[ stageDependencies.BuildStg.build.outputs['test.test'] ]
    steps:
    - script: |
        cp $(Build.Repository.LocalPath)/scripts/test.sh $(Build.ArtifactStagingDirectory)/acrconnect-installer-cli-$(test)[linux-out].sh
        sed -i 's/aivversion/$(test)/g' acrconnect-installer-cli-$(test)[linux-out].sh
        
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'acrconnect-installer-cli-$(test)[linux-x64]'
