stages:
- stage: BuildStg
  jobs:
    - job: build
      pool: 
        name: Azure Pipelines
        vmImage: ubuntu-18.04
      steps:
      - task: CmdLine@2
        displayName: 'Get version info'
        inputs:
          script: |
            aiv=1.0.0
            div=2.2.0
            echo "##vso[task.setvariable variable=aiv;]$aiv"
            echo "##vso[task.setvariable variable=div;isOutput=true]$div"
          name: DetermineResult
      - bash: |
          echo "aiv=$(aiv)"
          echo "div=$(div)"
